init:
    storage: !service
        name: storage
        instance: !include { path: ../../wfcommon/config/storage.yaml }

input: !service
    name: events  # Use embedded wfdriver to receive events
    instance: !function {}

#input: !http-in { port: 8888 }

#input: !stdio-in {}

collector: !multi
    children:
        aggregator : !buffer
            period: 600
            collector: !aggregator
                storage : !service
                    name: storage
        current : !flush
            period: 10
            collector: !user
                choices:
                    root: !xmlfile
                        path: /var/lib/wfrog/wfrog-current.xml
                        storage : !service
                            name: storage
                    default: !xmlfile
                        path: data/wfrog-current.xml
                        storage : !service
                            name: storage

embed:
    wfdriver: { config: ../../wfdriver/config/embedded.yaml }

logging:
    level: info
    filename: !user
        choices:
            root: /var/log/wflogger.log
            default: wflogger.log

    ## By default wfrog uses a Rotating file handler. To set up different handlers
    ## uncomment the following section. (Warning: does not work under python > 2.7)
    #handlers:
    #    default:
    #        level: debug
    #        handler: !include
    #            path: ../../wfcommon/config/loghandler.yaml
    #            variables:
    #                process: wflogger
    #    #mail:
    #    #    level: critical
    #    #    handler: !include
    #    #        path: ../../wfcommon/config/mailloghandler.yaml


