renderer: !multi
    parallel: true
    children:
        ## Uncomment to activate PWS Weather for you publisher
        #pwsweather: !pwsweather
        #    id: STATION_ID
        #    password: PASSWORD
        #    storage: !service
        #        name: storage
        #    period: 300
        
        ## Uncomment to activate Wetter.com publisher
        # SetUp: http://www.wetter.com/community/wetternetzwerk/admin/api/
        # Please use for first setup test: True to test publishing. Check logs!
        #wettercom: !wettercom
        #    username: YOUR_STATION_ID
        #    password: YOUR_STATION_PASSWORD
        #    storage: !service
        #        name: storage
        #    test: False
        #    period: 900

        ## Uncomment to activate Weather Underground publisher
        #wunderground: !wunderground
        #    id: STATION_ID
        #    password: PASSWORD
        #    storage: !service
        #        name: storage
        #    period: 300

        ## Uncomment to publish files by ftp (compatible with http server)
        #ftp: !scheduler
        #    period: 600  # in seconds
        #    delay: 60 # in seconds, delay before start rendering
        #    renderer: !ftp
        #        host: HOST.COM 
        #        username: USERNAME
        #        password: PASSWORD
        #        directory: DIRECTORY
        #        renderers:
        #            3hours.html: !file
        #                path: /tmp/3hours.html
        #                renderer: !include
        #                    path: default/3hours.yaml
        #            24hours.html: !file
        #                path: /tmp/24hours.html
        #                renderer: !include
        #                    path: default/24hours.yaml
        #            30days.html: !file
        #                path: /tmp/30days.html
        #                renderer: !include
        #                    path: default/30days.yaml
        #            365days.html: !file
        #                path: /tmp/365days.html
        #                renderer: !include
        #                    path: default/365days.yaml
        #            ## Uncomment to activate www.meteoclimatic.com ftp publisher
        #            #meteoclimatic.txt: !file
        #            #    path: /tmp/meteoclimatic.txt
        #            #    renderer: !meteoclimatic
        #            #        id: STATION_ID  
        #            #        storage: !service
        #            #            name: storage

        # Http publishing (default)
        http: !http
            cookies: [ units ]
            root: !include
                path: default/24hours.yaml
            renderers:
                3hours.html: !include
                    path: default/3hours.yaml
                24hours.html: !include
                    path: default/24hours.yaml
                7days.html: !include
                    path: default/7days.yaml
                30days.html: !include
                    path: default/30days.yaml
                365days.html: !include
                    path: default/365days.yaml
                check: !include
                    path: default/check.yaml
                ## Uncomment to activate www.meteoclimatic.com http publisher
                #meteoclimatic.txt: !file
                #    path: /tmp/meteoclimatic.txt.txt
                #    renderer: !meteoclimatic
                #        id: STATION_ID 
                #        storage: !service
                #            name: storage

